--- #YAML:1.0
name:               podium
version:            0.01
abstract:           POD-based presentation and website builder
author:
    - Andy Lester <andy@petdance.com>
license:            artistic2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Always:       0
    File::Slurp:        0
    Getopt::Long:       0
    Pod::Simple:        3.13
    Pod::Simple::HTML:  0
    Template:           0
    Test::More:         0
    YAML:               0
resources:
    bugtracker:   http://github.com/petdance/ack
    homepage:     http://betterthangrep.com/
    license:      http://dev.perl.org/licenses/
    MailingList:  http://groups.google.com/group/ack-users
    repository:   git://github.com/petdance/ack.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
